import { mergeApplicationConfig, ApplicationConfig } from '@angular/core';
import { provideServerRendering } from '@angular/platform-server';
import { appConfig } from './app.config';

/**
 * Server Application Configuration
 * 
 * This configuration is merged with the client config when running on the server.
 * 
 * Key providers:
 * - provideServerRendering: Enables server-side rendering
 * 
 * When converting your app:
 * - This file is usually auto-generated by Angular CLI
 * - You typically don't need to modify this unless you have server-specific providers
 * - Server-specific providers (like API interceptors) can be added here
 */
const serverConfig: ApplicationConfig = {
  providers: [
    provideServerRendering(),
  ]
};

export const config = mergeApplicationConfig(appConfig, serverConfig);
